### ISSUE TITLE
Run performance tests nightly instead of on commit

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#593]
## Summary

The performance tests are necessary, but also take a very long time to run. I'm thinking that we should reorganize the CircleCI workflows so that those tests are run nightly on `main`, while the other tests still get run on each commit to `main` and on PRs.

## Additional details

The main benefit would be faster CI on PRs.

## Next steps

1. Reorganize the CircleCI config so that the performance tests are run on a nightly basis.
2. Ensure that coverage doesn't drop based on not running the performance tests in PRs.
3. Figure out how to check the nightly tests, so that any failures don't go unnoticed.

**Comment by tsalo** [comment]
```yaml
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:

  make_py36_env:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/NiMARE
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps10-{{ checksum "nimare/info.py" }}-{{ checksum "setup.py" }}
      - run:  # will overwrite NiMARE installation each time
          name: Generate environment
          command:  |
            if [[ -e /opt/conda/envs/py36_env ]]; then
                echo "Restoring environment from cache"
                source activate py36_env
            else
                conda create -n py36_env python=3.6 -yq
                source activate py36_env
                pip install -e .[tests,doc,peaks2maps-cpu]
            fi
            python setup.py install --user
      - save_cache:  # environment cache tied to requirements
          key: deps10-{{ checksum "nimare/info.py" }}-{{ checksum "setup.py" }}
          paths:
            - "/opt/conda/envs/py36_env"

  test_py36_minimum:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/NiMARE
      - run:  # will overwrite NiMARE installation each time
          name: Generate environment
          command:  |
            conda create -n py36_min_env python=3.6 -yq
            source activate py36_min_env
            pip install -e .[minimum,tests,peaks2maps-cpu]
            python setup.py install --user
      - run:
          name: Run tests
          command:  |
            apt-get update
            apt-get install -yqq make
            source activate py36_min_env
            make unittest

  test_py36:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - attach_workspace:  # get NiMARE
          at: /tmp
      - restore_cache:  # load environment
          key: deps10-{{ checksum "nimare/info.py" }}-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command:  |
            apt-get update
            apt-get install -yqq make
            source activate py36_env
            make unittest
            mkdir /tmp/src/coverage
            mv /tmp/src/NiMARE/.coverage /tmp/src/coverage/.coverage.py36
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/coverage/.coverage.py36

  test_py37:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/NiMARE
      - run:  # will overwrite NiMARE installation each time
          name: Generate environment
          command:  |
            conda create -n py37_env python=3.7 -yq
            source activate py37_env
            pip install -e .[tests,peaks2maps-cpu]
            python setup.py install --user
      - run:
          name: Run tests
          command:  |
            apt-get update
            apt-get install -yqq make
            source activate py37_env
            make unittest

  test_py38:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/NiMARE
      - run:  # will overwrite NiMARE installation each time
          name: Generate environment
          command:  |
            conda create -n py38_env python=3.8 -yq
            source activate py38_env
            pip install pip -U
            pip install -e .[tests,peaks2maps-cpu]
            python setup.py install --user
      - run:
          name: Run tests
          command:  |
            apt-get update
            apt-get install -yqq make
            source activate py38_env
            make unittest

  test_py39:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/NiMARE
      - run:  # will overwrite NiMARE installation each time
          name: Generate environment
          command:  |
            conda create -n py39_env python=3.9 -yq
            source activate py39_env
            pip install pip -U
            pip install -e .[tests,peaks2maps-cpu]
            python setup.py install --user
      - run:
          name: Run tests
          command:  |
            apt-get update
            apt-get install -yqq make
            source activate py39_env
            make unittest

  test_performance_estimators:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - attach_workspace:  # get NiMARE
          at: /tmp
      - restore_cache:  # load environment
          key: deps10-{{ checksum "nimare/info.py" }}-{{ checksum "setup.py" }}
      - run:
          name: Linting
          command:  |
            apt-get update
            apt-get install -yqq make
            source activate py36_env
            make test_performance_estimators
            mkdir /tmp/src/coverage
            mv /tmp/src/NiMARE/.coverage /tmp/src/coverage/.coverage.performance_estimators
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/coverage/.coverage.performance_estimators

  test_performance_correctors:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - attach_workspace:  # get NiMARE
          at: /tmp
      - restore_cache:  # load environment
          key: deps10-{{ checksum "nimare/info.py" }}-{{ checksum "setup.py" }}
      - run:
          name: Test reasonable output for combinations of estimators/kernels/correctors
          no_output_timeout: 30m
          command:  |
            apt-get update
            apt-get install -yqq make
            source activate py36_env
            make test_performance_correctors
            mkdir /tmp/src/coverage
            mv /tmp/src/NiMARE/.coverage /tmp/src/coverage/.coverage.performance_correctors
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/coverage/.coverage.performance_correctors

  test_performance_smoke:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - attach_workspace:  # get NiMARE
          at: /tmp
      - restore_cache:  # load environment
          key: deps10-{{ checksum "nimare/info.py" }}-{{ checksum "setup.py" }}
      - run:
          name: Test reasonable output for combinations of estimators/kernels/correctors
          no_output_timeout: 30m
          command:  |
            apt-get update
            apt-get install -yqq make
            source activate py36_env
            make test_performance_smoke
            mkdir /tmp/src/coverage
            mv /tmp/src/NiMARE/.coverage /tmp/src/coverage/.coverage.performance_smoke
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/coverage/.coverage.performance_smoke

  merge_coverage:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - restore_cache:
          key: deps10-{{ checksum "nimare/info.py" }}-{{ checksum "setup.py" }}
      - run:
          name: Merge coverage files
          command: |
            apt-get update
            apt-get install -yqq curl
            source activate py36_env
            cd /tmp/src/coverage/
            coverage combine
            coverage xml
      - store_artifacts:
          path: /tmp/src/coverage
      - codecov/upload:
          file: /tmp/src/coverage/coverage.xml

  build_docs:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - attach_workspace:  # get NiMARE
          at: /tmp
      - restore_cache:  # load environment
          key: deps10-{{ checksum "nimare/info.py" }}-{{ checksum "setup.py" }}
      - run:
          name: Build documentation
          command: |
            source activate py36_env
            apt-get update
            apt-get install -yqq make
            make -C docs html
          no_output_timeout: 30m
      - store_artifacts:
          path: /tmp/src/NiMARE/docs/_build/html

  style_check:
    working_directory: /tmp/src/NiMARE
    docker:
      - image: continuumio/miniconda3
    steps:
      - attach_workspace:  # get NiMARE
          at: /tmp
      - restore_cache:  # load environment
          key: deps10-{{ checksum "nimare/info.py" }}-{{ checksum "setup.py" }}
      - run:
          name: Linting
          command:  |
            source activate py36_env
            flake8 /tmp/src/NiMARE/nimare
      - store_artifacts:
          path: /tmp/data/lint

workflows:
  version: 2.1
  run_tests:
    jobs:
      - make_py36_env
      - test_py36_minimum
      - test_py36:
          requires:
            - make_py36_env
      - test_py37
      - test_py38
      - test_py39
      - test_performance_smoke:
          requires:
            - make_py36_env
      - build_docs:
          requires:
            - make_py36_env
      - style_check:
          requires:
            - make_py36_env
      - merge_coverage:
          requires:
            - test_py36
            - test_performance_smoke
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - make_py36_env
      - test_py36_minimum
      - test_py36:
          requires:
            - make_py36_env
      - test_py37
      - test_py38
      - test_py39
      - test_performance_estimators:
          requires:
            - make_py36_env
      - test_performance_correctors:
          requires:
            - make_py36_env
      - test_performance_smoke:
          requires:
            - make_py36_env
      - build_docs:
          requires:
            - make_py36_env
      - style_check:
          requires:
            - make_py36_env
      - merge_coverage:
          requires:
            - test_py36
            - test_performance_estimators
            - test_performance_correctors
            - test_performance_smoke
```
